package com.sample

import com.techsoft.partselector.util.InputParameters;
import com.techsoft.partselector.model.Part;
import com.techsoft.partselector.model.HashVector;
import com.techsoft.partselector.util.RuleResult;
import com.techsoft.partselector.util.AuxiliaryMethods;

/*rule "Geometrical Rule"
	when
		InputParameters( $params : parameters,
						 parameters["Dbore"] != null,
						 parameters["MinGap"] != null,
						 parameters["Lclamp"] != null,
						 parameters["MinOverlap"] != null,
						 parameters["MaxOverlap"] != null,
						 parameters["WasherMinGap"] != null,
						 parameters["WasherMinOverlap"] != null)
		$washer : Washer( $innerD : innerDiameter,
						  $outerD : outerDiameter,
						  $thickness : thickness)
		$screwNut : ScrewNut ( $nominalD : nominalDiameter,
							   $nutThread : thread,
							   $height : height,
							   (Number)$params["Dbore"] >= $nominalD + (Number)$params["MinGap"])
		$screw : Screw( 
						$nutThread == thread,
						$nominalD == nominalDiameter,
						length >= (Number)$params["Lclamp"] + $height + $thickness + $thickness + (Number)$params["MinOverlap"],
						length <= (Number)$params["Lclamp"] + $height + $thickness + $thickness + (Number)$params["MaxOverlap"],
						$innerD >= nominalDiameter + (Number)$params["WasherMinGap"],
						$innerD < headDiameter,
						$outerD >= headDiameter + (Number)$params["WasherMinOverlap"]
						)
	then
		System.out.println( "Screw: " + $screw.getName() + ", ScrewNut: " + $screwNut.getName() + ", Washer: " + $washer.getName());
end*/
/*function Number AuxiliaryMethods.getField(String name, Object object) {
	//System.out.println(name + " " + object.getClass().getName());
	return (Number)object.getClass().getMethod(name).invoke(object);
}*/

rule "Geometrical Rule"
	when
		InputParameters( $params : parameters,
						 parameters["Dbore"] != null,
						 parameters["MinGap"] != null,
						 parameters["Lclamp"] != null,
						 parameters["MinOverlap"] != null,
						 parameters["MaxOverlap"] != null,
						 parameters["WasherMinGap"] != null,
						 parameters["WasherMinOverlap"] != null,
						 parameters["Screw"] != null,
						 parameters["ScrewNut"] != null,
						 parameters["Washer"] != null)
		$washer : Part(
						 ((Class)$params["Washer"]).isAssignableFrom(class))
		$screwNut : Part(
						   ((Class)$params["ScrewNut"]).isAssignableFrom(class),
						   (Number)$params["Dbore"] >= AuxiliaryMethods.getField("getNominalDiameter", $screwNut) + (Number)$params["MinGap"])
		$screw : Part(
						((Class)$params["Screw"]).isAssignableFrom(class),
						AuxiliaryMethods.getField("getThread", $screwNut) == AuxiliaryMethods.getField("getThread", $screw),
						AuxiliaryMethods.getField("getNominalDiameter", $screwNut) == AuxiliaryMethods.getField("getNominalDiameter", $screw),
						AuxiliaryMethods.getField("getLength", $screw) >= (Number)$params["Lclamp"] + AuxiliaryMethods.getField("getHeight", $screwNut) + 2 * AuxiliaryMethods.getField("getThickness", $washer) + (Number)$params["MinOverlap"],
						AuxiliaryMethods.getField("getLength", $screw) <= (Number)$params["Lclamp"] + AuxiliaryMethods.getField("getHeight", $screwNut) + 2 * AuxiliaryMethods.getField("getThickness", $washer) + (Number)$params["MaxOverlap"],
						AuxiliaryMethods.getField("getInnerDiameter", $washer) >= AuxiliaryMethods.getField("getNominalDiameter", $screwNut) + (Number)$params["WasherMinGap"],
						AuxiliaryMethods.getField("getInnerDiameter", $washer) < AuxiliaryMethods.getField("getHeadDiameter", $screw),
						AuxiliaryMethods.getField("getOuterDiameter", $washer) >= AuxiliaryMethods.getField("getHeadDiameter", $screw) + (Number)$params["WasherMinOverlap"])
	then
		HashVector result = new HashVector();
		result.addPart($screw);
		result.addPart($screwNut);
		result.addPart($washer);
		RuleResult.getInstance().addResult(result);
		System.out.println( "Screw: " + $screw.getName() + ", ScrewNut: " + $screwNut.getName() + ", Washer: " + $washer.getName());
end